# Generated by Django 2.1.7 on 2019-03-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_space_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.Author'),
            preserve_default=False,
        ),
    ]
